export const TODO_LIST_FAILED = 'TODO_LIST_FAILED';
export const TODO_LIST_LOADDATA = 'TODO_LIST_LOADDATA';
export const TODO_LIST_LOADING = 'TODO_LIST_LOADING';
export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS';

export const TODO_LIST_LOADDATA_ALL = 'TODO_LIST_LOADDATA_ALL';
export const GET_TODO_LIST_ALL = 'GET_TODO_LIST_ALL';

export const GET_KANBAN_TODO_LIST_DATA = 'GET_KANBAN_TODO_LIST_DATA';
export const GET_KANBAN_TODO_SUCCESS = 'GET_KANBAN_TODO_SUCCESS';
export const GET_KANBAN_TODO_ERROR = 'GET_KANBAN_TODO_ERROR';

export const UPDATE_TODO_STAGE = 'UPDATE_TODO_STAGE';
export const UPDATE_TODO_STAGE_SUCCESS = 'UPDATE_TODO_STAGE_SUCCESS';

export const GET_TODO = 'GET_TODO';
export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';

export const SET_CURRENT = 'SET_CURRENT';
export const SET_CURRENT_SUCCESS = 'SET_CURRENT_SUCCESS';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const TODO_ERROR = 'TODO_ERROR';
export const SET_LOADING = 'SET_LOADING';

export const TODO_FILTER_LIST = "TODO_FILTER_LIST"
export const TODO_FILTER_LIST_SUCCESS = "TODO_FILTER_LIST_SUCCESS"
export const TODO_FILTER_LIST_ERROR = "TODO_FILTER_LIST_ERROR"
// export const ADD_TODO = 'ADD_TODO';

// export const SET_LOADING = 'SET_LOADING';
