export const USER_PERMISSION_LOAD_BY_ONE_SUCCESS = "USER_PERMISSION_LOAD_BY_ONE_SUCCESS";
export const GET_USER_PERMISSION_BY_ONE_DATA = "GET_USER_PERMISSION_BY_ONE_DATA";
export const USER_PERMISSION_LOAD_BY_ONE_ERROR = "USER_PERMISSION_LOAD_BY_ONE_ERROR";
